### ISSUE TITLE
Meta-ZSDETR Code

### ISSUE THREAD

**Issue by nlhenderson17** [zhanglu-cst/zhanglu-cst#1]
Hi,

I was wondering if you plan to release the source code for the paper "Meta-ZSDETR: Zero-shot DETR with Meta-Learning"?

Thank you!

**Comment by zhanglu-cst** [comment]
I will be open source, but I have been busy writing my graduation thesis recently, so I haven't had time to sort out the code. I will do this after I finish my graduation thesis.

**Comment by zhanglu-cst** [comment]
solved
